# Generated by Django 4.2.2 on 2023-07-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenralUser',
            new_name='GeneralUser',
        ),
    ]
